name: checkinwithme
channels:
  - defaults
dependencies:
  - aiofiles
  - ipython
  - jinja2
  - networkx
  - pandas
  - pytest
  - sqlalchemy
  - sqlalchemy-utils
  - pip:
    - fastapi
    - pydantic
    - uvicorn
prefix: C:\Users\shagg\Anaconda3\envs\checkinwithme

