name: checkin
channels:
  - defaults
dependencies:
  - aiofiles
  - ipython
  - jinja2
  - networkx
  - pandas
  - pip
  - pytest
  - sqlalchemy
  - sqlalchemy-utils
  - pip:
    - dash
    - fastapi
    - pydantic
    - uvicorn
    - streamlit
